name: Publish

on:
  create:
    tags:
      - v*

jobs:
  build:
    name: "Build NextJS"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/lavalleeale/lambda:latest
  test:
    name: "Test with Cypress"
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Create file
        run: |
          echo 'SESSION_PASSWORD="ac766c422186d9018f0ec7c6344d01aa"' > .env
          echo 'DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres?schema=public"' >> .env
      - uses: actions/setup-node@master
        with:
          node-version: 16.13
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Setup Database
        run: yarn run prisma migrate deploy && yarn run prisma generate

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          build: yarn build
          start: yarn start
