name: Publish

on:
  create:
    tags:
      - v*

jobs:
  build:
    name: "Build NextJS"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/lavalleeale/lambda:latest
  test:
    name: "Test with Cypress"
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Create file
        run: |
          echo 'JWT_PRIVATE="-----BEGIN RSA PRIVATE KEY-----\nMIIJJwIBAAKCAgEA3dIS0/mPzByLwf5PVq3WPCtypWOTS+5Ti5rcfW2C9z9JkGEd\n2jIZJREtDfvgvirPNajOVx2nv/wb4Lnjkcr8vpSnu619PQB6eod6heQrsIAGr7Gh\nLkb0wsgoxtqORuoHjeD56jYlXtMiYALea8jzfI1YR+crwjml9UKog7TtHErYEmi8\nNQBi/csw1jiPWPxk/yatDtOj+PtNRv2HuwjckoprZYmp3LuvgwA+2/ozPoPCvNUH\na0Gq0h2UUiaU39cIGZ+ojhaG0Iy9O3n3STM5cWRUTj1BWbfdIRCoPZeHeQRMRBsh\nFyH8VcdIfuiCF3UaTkbJEo2AdtogoM9fHghPmo5+eIbCB8qYnC31+Gkax/82WEuG\nZQwAkbzOf29DgMJCb323eUIh2fED2GENlwhSTLQhrMX24N3wfjPCkYYRiQDTxD/b\n5bLGbnlPV6slk8EQKT2OxOjxwfJV4VSa8OUfk3IbGE9Jz3UM3TlnoXonG1Eetjsb\nGVQF7eDGWsqZhU3kQRAdhAb4ERXwrAQyhrkazDXyOgoXIDYqt1GmKIPKlss9z8Yf\nLlMQioIFi4XfU5bLvHzw6V6xochb+q6M+RDQDca7OzKx8rfOACsi4/vqEwuVC9YM\ngDMAFuH6bvBP6cV+rYq93gUjp3KPsz493ZN8K7Z8QdNEzPaD64ic9Dg2siUCAwEA\nAQKCAgB4PJrAFBKCDSckbHkM/wWVb+ehBqydB/55OeQyiN3or4FspXfNAkLm+Lx3\nTASyj/npmCrgxc5cHoft9FUKfgEqPOH+tTehjVTWfgFH+jpEXeFB8wLvVr7tphmU\nUHu2rLyTh1NwRRFUqRWE/Yka274/0U39C62Ihj8TBqLZYYT1RQyCTgtWn3MJJs6+\nD8KD9au5Mnm0A7xqBa4JwPuFwnPtauJ0E37ji0jDtapdCu4kAL/aI4718I5rfmUb\ncpZYDvLxEL4I5uUEvoUEbERChWWptTyNfF6kBynx9ll7qVthmZbNg/cX1vA0fuUp\nBVce5/buXyg2ykTMJ8hv4ngoi1C58BPf/iFea5f1koQocfY10m0pljVNqAyF7RRN\nZ0r3n5CZBMQcJ/b0YPmwOHeX41Emc5biM/GG1+AyLvbHbqd/WmcDq4nCEmjYSW6Z\n3AyFCGjjo+1QaqulRIcCX5FETOchgdxEDFcH5WT2ZxxGudjV7nY4Q0Klxv/XVtTh\nrtDAToxuxTj9anj8XQynouGGXMX4cWZros89WgTzmL061jSyGZkpbQ73YwbS3YLA\ndIKyPvqnPswk8kI38wsomGp7cpeeJvQAvhRO2+55KmhjxwIKQh7N2pRrLcsAmUpm\n86EqsdWN/xV21TUfHBTQTBd1/lxZW8wjMgqpHsQyCwkZ69WXsQKCAQEA7vBlT6dS\ny5LEB2+GZSPgL5FYlclYxk17JP5bL0LsMg/FFbbuOh/1vKewYC6iNQ3MMrmrH4Np\nxlnWaQeIzFIcGximGC2w1ZwjoqIl+o2kvtn5Be6HMdlWNJoCB389h2e3aIJZuolm\n5MWbN/F9WtGRGFA9tsXZPj8tBmV93p4NZVIAxtAQCWa5zNuv6QwBDGRMJURiSSkz\nwLfYB71PQA9qH5IyFCihTi52yiecA3FtU888222jww8pBDkaySNuSebNWHcZiqcv\nS/F4UocJjNia8SkpyvqntiyFZdrZ7/okfHKq3CEWuWX4IYeifJpWM4hDiftPkC3k\nnbbFHOjrGa/WxwKCAQEA7ajEXOKFoPoEd2W0/alPAIo/pkvDrgDuklH0QiH32WJs\n6VWZyhiwotVjVvlqaaSmwHAuFDElcq8r0bMPmsSZehRCqJtmjtqZV9K66MlGdXFH\nym2BbTcIuVmzRBag2CxiTMa8gFImHhgSYqRdNehhCQM7FDWXpTNor2XYmaOOg0Xa\nk+empBNpDmLAUzyX9lwfj8d9donl0eAyLcx1Y1PNwp7wlOAQTiRN+OokuhGb4Sy1\nLarLKxsIgp9CdDEpBY5NNfRJa7PY88sVUNQ/yfiVY4tU9ftZWdEDsJB2FeyvRREz\nRwRkhSluvRIB7vuw9P4zHoqU0plDT2UOGPOArldTswKCAQA757uOx+WjMm3Ba32n\nd+IqKuepzixas2xPbxIPfFjZiEiiVBXQLtkebnBy/N4gLRBoG1LC+OCZIUb3WDM8\n/s0bIgfqgfIW7CmnCb453i9SxjV//jiZD+NkFsSxen5Dp4Y9RokWkoJgkwaCdSI3\nldkp3lxKqbn4uEAinWl8WeYD5BZbwihzIvUsXlvxMthEchUBNu7pZtIZ3D3mWtk2\nt2ak+bNiiHlAr7eKoXmlB1ggrhGU9h0bt35SF7sWeLKbBqmvJ1UZBSd/g8/l6QNE\n872M/wQCZuuLaggb7E29s9pX9SvPOuCGpQEb7vSXBt7b1qsQOhjNjiQGQp+Syva+\nnu5bAoIBAG+gO0rdYqJvjDWAYfha066PQMIdB/XsniG/uJhvV/iU0E7wU+GmoyB4\nVcZ+M8sW+POePSZixxIM0OoXzpaFDQlYBs8m3o7ugePMKNo534w9/thHgukHVmOo\njBjJABdJEYq6NcOX0iuEZu5KATXWxezzxYYCfg2sDdmEXq4bMk7aOoYJ4i1iqI+H\nNopiBYZDUte3fWh18KoZQbhdNi3HKPfmq11huIbbanwljcaPisXCt/6RIAhJFEA2\nCYKFrJzdb8qNyQZ7XMV1d7eVWbjFt3Uf9nHq8tbK447E65H0r4YjRBBxMb2R7l+D\n28CiG0WXN+96a9hXAFSERJDXnnNEtR0CggEAAJ4JogEdmb5kdkQx/sBLv4CcJTEc\npT89MTipGckQ2hbNvuHTsrwf8dxscqDJn8JVHDDa5ipLO/SQOzhY2bCqgcrr+gLz\njfYTL91FYqPhxk+FZ/CBgTUb7XJucu2JwNkPVh1/uXY7Se/ylQyqf3rK16O4DRss\nVNHMpsxfEIzxYIYGw8MfYYyV8PXYMozyLc2IDLQRv6+aixmL+El2kgaxRdvD2Lkd\nCi9VI0ctFQpUKZbQLN9LXsYfSZO5yVzVm4vg2rWw7iVBgaCmTrMjkzguiBc5Sthv\nNt4L45u7Fdy95zqsnzOUKbgnizDuYe3XBsO5AbrMsWDq1htvZ6hefjqqsw==\n-----END RSA PRIVATE KEY-----\n"' > .env
          echo 'JWT_PUBLIC="-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3dIS0/mPzByLwf5PVq3W\nPCtypWOTS+5Ti5rcfW2C9z9JkGEd2jIZJREtDfvgvirPNajOVx2nv/wb4Lnjkcr8\nvpSnu619PQB6eod6heQrsIAGr7GhLkb0wsgoxtqORuoHjeD56jYlXtMiYALea8jz\nfI1YR+crwjml9UKog7TtHErYEmi8NQBi/csw1jiPWPxk/yatDtOj+PtNRv2Huwjc\nkoprZYmp3LuvgwA+2/ozPoPCvNUHa0Gq0h2UUiaU39cIGZ+ojhaG0Iy9O3n3STM5\ncWRUTj1BWbfdIRCoPZeHeQRMRBshFyH8VcdIfuiCF3UaTkbJEo2AdtogoM9fHghP\nmo5+eIbCB8qYnC31+Gkax/82WEuGZQwAkbzOf29DgMJCb323eUIh2fED2GENlwhS\nTLQhrMX24N3wfjPCkYYRiQDTxD/b5bLGbnlPV6slk8EQKT2OxOjxwfJV4VSa8OUf\nk3IbGE9Jz3UM3TlnoXonG1EetjsbGVQF7eDGWsqZhU3kQRAdhAb4ERXwrAQyhrka\nzDXyOgoXIDYqt1GmKIPKlss9z8YfLlMQioIFi4XfU5bLvHzw6V6xochb+q6M+RDQ\nDca7OzKx8rfOACsi4/vqEwuVC9YMgDMAFuH6bvBP6cV+rYq93gUjp3KPsz493ZN8\nK7Z8QdNEzPaD64ic9Dg2siUCAwEAAQ==\n-----END PUBLIC KEY-----\n"' >> .env
          echo 'DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres?schema=public"' >> .env
      - uses: actions/setup-node@master
        with:
          node-version: 16.13
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Setup Database
        run: yarn run prisma migrate deploy && yarn run prisma generate

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          build: yarn build
          start: yarn start
