name: Build

on: [push, pull_request]

jobs:
  # build:
  #   name: "Build NextJS"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master

  #     - name: Cache node modules
  #       uses: actions/cache@v2
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-

  #     - uses: actions/setup-node@master
  #       with:
  #         node-version: 16.13

  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile

  #     - name: Build
  #       run: yarn build
  test:
    name: "Test with Cypress"
    runs-on: ubuntu-latest
    # needs: build
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: development
          POSTGRES_USERNAME: development
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: actions/setup-node@master
        with:
          node-version: 16.13
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Setup Database
        run: yarn run prisma migrate reset --force

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: yarn build
          start: yarn start
